USE [master]
GO

/****** Object:  Database [CDCT]    Script Date: 2020/12/22 上午 11:19:41 ******/
CREATE DATABASE [CDCT]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CDUT2', FILENAME = N'H:\SQLData\CDCT.mdf' , SIZE = 231348224KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'CDUT2_log', FILENAME = N'H:\SQLData\CDCT_log.ldf' , SIZE = 21287424KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CDCT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CDCT] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CDCT] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CDCT] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CDCT] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CDCT] SET ARITHABORT OFF 
GO

ALTER DATABASE [CDCT] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CDCT] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CDCT] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CDCT] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CDCT] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CDCT] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CDCT] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CDCT] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CDCT] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CDCT] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CDCT] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CDCT] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CDCT] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CDCT] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CDCT] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CDCT] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CDCT] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CDCT] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CDCT] SET  MULTI_USER 
GO

ALTER DATABASE [CDCT] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CDCT] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CDCT] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CDCT] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [CDCT] SET  READ_WRITE 
GO


